### ISSUE TITLE
loadWasmModule() is undefined.

### ISSUE THREAD

**Issue by trasherdk** [woodser/xmr-sample-app#1]
In `wallet_worker.js` 
the `MoneroUtils.loadWasmModule()` call
throws `MoneroUtils.loadWasmModule is not a function`

Did I miss something?
```
  async function runWallet() {
    console.log("WORKER loading module");
    try {
      await MoneroUtils.loadWasmModule();
    }
    catch (e) {
      console.log(e.message);
      return false;
    }
    console.log("done loading module");
```
My environment: **Slackware 14.2 x64**
```
# uname -a
Linux 4.4.208 #1 SMP Fri Jan 10 02:31:26 CET 2020 x86_64 Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz GenuineIntel GNU/Linux

# apachectl -v
Server version: Apache/2.4.39 (Unix)
Server built:   Apr  6 2019 14:30:06

# node -v
v12.13.0

# npm -v
6.13.6

# python -V
Python 2.7.17
```

**Comment by woodser** [comment]
It appears you are using a non-master branch of xmr-sample-app which would require a non-master branch of monero-javascript.

If you only want to use a wallet or daemon over RPC or a keys-only wallet, the master branches should support those.

If you want to use experimental support for a client-side wallet running in a web worker as demonstrated in wallet_worker.js, the latest branches of xmr-sample-app and monero-javascript are needed, and xmr-sample-app needs npm linked to use the monero-javascript branch instead of the npm repository:

1. git clone https://github.com/monero-ecosystem/monero-javascript.git
2. cd /path/to/monero-javascript
3. git checkout wasm83_start_syncing
4. npm link
5. cd path/to/xmr-sample-app
6. git checkout wasm68_onward
7. npm link monero-javascript

**Comment by trasherdk** [comment]
Yes. I'm on a branch off `wasm68_onward`.
I added the `try {} catch()` thingy to get some response.
Doing above steps made it run until I got CORS errors, but that's on me.
Step 4 `npm link` did surprise me some, as it made `monero-javascript` a global install.

Okay. Thanks. Onwards...

**Comment by trasherdk** [comment]
This is driving me nuts.. 
I'm getting `401 Unauthorized` on all RPC calls in `wallet_worker.js` ???
```
Connecting to monero-daemon-rpc... wallet_worker.js:61:13
getHeight(): StatusCodeError: 401 - "<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>" wallet_worker.js:89:15
Daemon height: 0 wallet_worker.js:91:13
Attempting to open wallet test_wallet_1... wallet_worker.js:105:15
StatusCodeError: 401 - "<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>"
Request: 'open_wallet' with params: {"filename":"test_wallet_1","password":"supersecretpassword123"} wallet_worker.js:108:15
```
Relevant code:
```
    const login = {
      deamon: {
        user: "superuser",
        pass: "abctesting123"
      },
      wallet: {
        user: "rpc_user",
        pass: "abc123"
      }
    }

    console.log("Connecting to monero-daemon-rpc...");

    let daemon = new MoneroDaemonRpc({uri: protocol + "://" + domain + ":38081"
      , user: login.deamon.user
      , pass: login.deamon.pass});

   let blockheight = 0;
    try {
==> blockheight = await daemon.getHeight(); <======= 401 Error
    }
    catch (e) {
      console.error("getHeight():", e.message);
    }
    console.log("Daemon height: " + blockheight);

    // connect to monero-wallet-rpc
    let walletRpc = new MoneroWalletRpc({uri: protocol + "://" + domain + ":38083"
    , user: login.wallet.user
    , pass: login.wallet.pass});
  
    // configure the rpc wallet to open or create
    let name = "test_wallet_1";
    let password = "supersecretpassword123";
    let restoreHeight = 453289;
    
    // open or create rpc wallet
    try {
      console.log("Attempting to open wallet " + name + "...");
==> await walletRpc.openWallet(name, password); <======= 401 Error
    } catch (e) {
      console.log(e);
```
Script to launch `monerod` and `monero-wallet-rpc`
```
start_daemon() {
	local SNAME="xmr-app-daemon"
	is_running ${SNAME} && return 1

	local DAEMON="${BIN}/monerod" 
	[ "${NETTYPE}" = "mainnet" ] || DAEMON="${DAEMON} --${NETTYPE}"

	DAEMON="${DAEMON} \
		--prune-blockchain \
		--data-dir ${DATA} \
		--log-file ${LOGS}/monerod.log \
		--confirm-external-bind \
		--rpc-bind-ip '0.0.0.0' \
		--rpc-login superuser:abctesting123 \
		--rpc-access-control-origins 'http://xmr-app.example.com'"

	screen -S "xmr-app-daemon-${NETTYPE}" -d -m  bash -c "${DAEMON}"
}

start_wallet() {
	local SNAME="xmr-app-rpc"
	is_running ${SNAME} && return 1

	local RPC="${BIN}/monero-wallet-rpc"
	[ "${NETTYPE}" = "mainnet" ] || RPC="${RPC} --${NETTYPE}"

	RPC="${RPC} \
		--daemon-address 'http://xmr-app.example.com:38081' \
		--daemon-login superuser:abctesting123 \
		--log-file ${LOGS}/monero-rpc.log \
		--confirm-external-bind \
		--rpc-bind-ip '0.0.0.0' \
		--rpc-bind-port 38083 \
		--rpc-login rpc_user:abc123 \
		--rpc-access-control-origins 'http://xmr-app.example.com' \
		--wallet-dir ${WALLETS}"

	screen -S "xmr-app-rpc-${NETTYPE}" -d -m  bash -c "${RPC}"
}
```

**Comment by woodser** [comment]
Depending on the browser, I've seen each RPC call report a 401 unauthorized as a challenge which the client then responds to.  Chrome does not report any errors.  Safari reports the 401 challenge and succeeds on the response.  Firefox fails on the first 401 which may be a security setting related to http and/or localhost.

**Comment by woodser** [comment]
What browser are you using?  Were you able to get it running from localhost?

**Comment by trasherdk** [comment]
I'm using Firefox 72.0.2, and I didn't try running on localhost.
My server running this thing, and the 3 monero blockchains, is 7000 Km away.

[xmr-sample-app](http://xmr-app.fumlersoft.dk/)

**Comment by trasherdk** [comment]
Comparing curl, postman and monero-javascript sessions in monero-wallet-rpc log-file show
that no response is given by monero-javascript to the `401` challenge.

It must be the responsibility of monero-javascript to build the response and reply,
or populate a `Authenticate` header before calling out.

I have the relevant parts of the log-file available, should you want them.

**Comment by woodser** [comment]
I have seen the same behavior of the library not responding to the authentication challenge in Firefox.  For the purpose of testing, can you confirm it works in a different browser?

**Comment by woodser** [comment]
https://github.com/monero-ecosystem/monero-javascript/issues/8

**Comment by trasherdk** [comment]
Just installed `Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)` to test.
I still don't like that browser.

**And, it does work in Chrome.**
